version: '2'
services:

    nginx:
        build: .
        image: umputun/nginx-le:latest
        hostname: nginx
        restart: always
        container_name: nginx

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        volumes:
            - ./etc/ssl:/etc/nginx/ssl
            - ./etc/service.conf:/etc/nginx/service.conf
            # - ./etc/service-example-2.conf:/etc/nginx/service2.conf # more services, should be service*.conf
            # - ./etc/stream-example-2.conf:/etc/nginx/stream2.conf # more streams, should be stream*.conf
            # - ./etc/conf.d:/etc/nginx/conf.d-le # configuration folder, all files from it will be added
            # - ./etc/stream.conf:/etc/nginx/stream.conf.d-le # streams configuration folder, all files from it will be added
        ports:
            - "80:80"
            - "443:443"

        environment:
            - TZ=America/New_York
            - LETSENCRYPT=true
            - LE_EMAIL=v0atmage@gmail.com
            - LE_FQDN=moat.chat
            #- SSL_CERT=le-crt.pem
            #- SSL_KEY=le-key.pem
            #- SSL_CHAIN_CERT=le-chain-crt.pem
